title: Google Summer of Code 2020

description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

logo: https://github.com/viniciusdc/GSoC/blob/master/assets/img/vector-graphi-gears-icon.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: False

google_analytics: False

# Build settings
theme: jekyll-theme-minimal
